version: '3'
services:
  reverseproxy:
    container_name: reverseproxy
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - application

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - "5432:5432"
    networks:
      - application

  # server:
  #   container_name: server
  #   build:
  #     context: ./
  #     dockerfile: server.dockerfile
  #   volumes:
  #     - ./src:/app/src
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - reverseproxy
  #   networks:
  #     - application

  client:
    container_name: client
    depends_on:
      - reverseproxy
    build:
      context: ./
      dockerfile: client.dockerfile
    volumes:
      - /app
      - /app/node_modules
    networks:
      - application

networks:
  application:
