version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - "5432:5432"

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    container_name: client
    build:
      context: ./
    ports:
      - 4200:4200
    volumes:
      - /app
      - /app/node_modules
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
